# Generated by Django 5.2.7 on 2026-09-24 08:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associations', '0002_alter_association_options_and_more'),
        ('members', '0003_importbatch_source_file_importbatch_source_headers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identificador')),
                ('question', models.CharField(max_length=300, verbose_name='enunciado')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('open', 'Abierta'), ('published', 'Resultado publicado'), ('cancelled', 'Anulada')], default='draft', max_length=16, verbose_name='estado')),
                ('closes_at', models.DateTimeField(verbose_name='cierre de la votación')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de apertura')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de publicación')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de anulación')),
                ('cancel_reason', models.CharField(blank=True, max_length=500, verbose_name='motivo de la anulación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='associations.association', verbose_name='asociación')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_polls', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
            ],
            options={
                'verbose_name': 'encuesta',
                'verbose_name_plural': 'encuestas',
                'ordering': ['-closes_at', 'question'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identificador')),
                ('label', models.CharField(max_length=200, verbose_name='texto')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.poll', verbose_name='encuesta')),
            ],
            options={
                'verbose_name': 'opción',
                'verbose_name_plural': 'opciones',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='polls.poll', verbose_name='encuesta')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='polls.polloption', verbose_name='opción')),
            ],
            options={
                'verbose_name': 'papeleta',
                'verbose_name_plural': 'papeletas',
            },
        ),
        migrations.CreateModel(
            name='PollRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_voted', models.BooleanField(default=False, verbose_name='ha votado')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poll_recipients', to='members.member', verbose_name='miembro')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='polls.poll', verbose_name='encuesta')),
            ],
            options={
                'verbose_name': 'destinatario de encuesta',
                'verbose_name_plural': 'destinatarios de encuesta',
            },
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['association', 'status', 'closes_at'], name='polls_poll_associa_d52cf8_idx'),
        ),
        migrations.AddConstraint(
            model_name='polloption',
            constraint=models.UniqueConstraint(fields=('poll', 'label'), name='unique_poll_option_label'),
        ),
        migrations.AddConstraint(
            model_name='pollrecipient',
            constraint=models.UniqueConstraint(fields=('poll', 'member'), name='unique_poll_recipient'),
        ),
    ]
