# Generated by Django 5.2.7 on 2026-09-21 07:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'ordering': ['name'], 'verbose_name': 'asociación', 'verbose_name_plural': 'asociaciones'},
        ),
        migrations.AlterModelOptions(
            name='associationaccess',
            options={'verbose_name': 'acceso a asociación', 'verbose_name_plural': 'accesos a asociaciones'},
        ),
        migrations.AlterModelOptions(
            name='associationrole',
            options={'verbose_name': 'rol de asociación', 'verbose_name_plural': 'roles de asociación'},
        ),
        migrations.AlterField(
            model_name='association',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='association',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='association',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activa'),
        ),
        migrations.AlterField(
            model_name='association',
            name='logo',
            field=models.ImageField(blank=True, upload_to='association-logos/%Y/%m/', verbose_name='logotipo'),
        ),
        migrations.AlterField(
            model_name='association',
            name='motto',
            field=models.CharField(blank=True, max_length=240, verbose_name='lema'),
        ),
        migrations.AlterField(
            model_name='association',
            name='name',
            field=models.CharField(max_length=180, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='association',
            name='primary_color',
            field=models.CharField(default='#1B4965', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Usa un color hexadecimal, por ejemplo #1B4965.')], verbose_name='color principal'),
        ),
        migrations.AlterField(
            model_name='association',
            name='secondary_color',
            field=models.CharField(default='#CAE9FF', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Usa un color hexadecimal, por ejemplo #CAE9FF.')], verbose_name='color secundario'),
        ),
        migrations.AlterField(
            model_name='association',
            name='slug',
            field=models.SlugField(max_length=80, unique=True, verbose_name='identificador para URL'),
        ),
        migrations.AlterField(
            model_name='association',
            name='timezone',
            field=models.CharField(default='Europe/Madrid', max_length=64, verbose_name='zona horaria'),
        ),
        migrations.AlterField(
            model_name='associationaccess',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_accesses', to=settings.AUTH_USER_MODEL, verbose_name='cuenta'),
        ),
        migrations.AlterField(
            model_name='associationaccess',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='associations.association', verbose_name='asociación'),
        ),
        migrations.AlterField(
            model_name='associationaccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='associationaccess',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='associationrole',
            name='access',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='associations.associationaccess', verbose_name='acceso'),
        ),
        migrations.AlterField(
            model_name='associationrole',
            name='role',
            field=models.CharField(choices=[('member', 'Músico'), ('board', 'Junta'), ('organizer', 'Contratista/organización'), ('director', 'Dirección musical'), ('admin', 'Administración'), ('platform', 'Administración de plataforma'), ('web_editor', 'Edición web')], max_length=24, verbose_name='rol'),
        ),
    ]
