# Generated by Django 5.2.7 on 2026-09-21 06:22

import apps.members.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='associations.association')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=80)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=180)),
                ('national_id', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('kind', models.CharField(choices=[('musician', 'Músico socio'), ('supporter', 'Socio colaborador/mecenas'), ('external', 'Colaborador musical externo')], default='musician', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=16)),
                ('photo', models.ImageField(blank=True, upload_to=apps.members.models.private_member_photo_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profiles', to=settings.AUTH_USER_MODEL)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='associations.association')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='MemberInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_instruments', to='members.instrument')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_instruments', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='associations.association')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='members.section'),
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('content_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('preview', 'Previsualización'), ('confirmed', 'Confirmada'), ('failed', 'Fallida')], default='preview', max_length=16)),
                ('mapping', models.JSONField(default=dict)),
                ('preview', models.JSONField(default=list)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_imports', to='associations.association')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('association', 'content_hash'), name='unique_import_file_per_association')],
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['association', 'status', 'last_name'], name='members_mem_associa_b618f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('association', 'external_id'), name='unique_member_external_id'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('account__isnull', False)), fields=('association', 'account'), name='unique_account_profile_per_association'),
        ),
        migrations.AddConstraint(
            model_name='memberinstrument',
            constraint=models.UniqueConstraint(fields=('member', 'instrument'), name='unique_member_instrument'),
        ),
        migrations.AddConstraint(
            model_name='memberinstrument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('member',), name='one_primary_instrument_per_member'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('association', 'name'), name='unique_section_name'),
        ),
        migrations.AddConstraint(
            model_name='instrument',
            constraint=models.UniqueConstraint(fields=('association', 'name'), name='unique_instrument_name'),
        ),
    ]
