# Generated by Django 5.2.7 on 2026-09-21 07:59

import apps.members.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0002_alter_association_options_and_more'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importbatch',
            options={'ordering': ['-created_at'], 'verbose_name': 'lote de importación', 'verbose_name_plural': 'lotes de importación'},
        ),
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['name'], 'verbose_name': 'instrumento', 'verbose_name_plural': 'instrumentos'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'miembro', 'verbose_name_plural': 'miembros'},
        ),
        migrations.AlterModelOptions(
            name='memberinstrument',
            options={'verbose_name': 'instrumento de miembro', 'verbose_name_plural': 'instrumentos de miembros'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order', 'name'], 'verbose_name': 'cuerda', 'verbose_name_plural': 'cuerdas'},
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_imports', to='associations.association', verbose_name='asociación'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de confirmación'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='content_hash',
            field=models.CharField(max_length=64, verbose_name='huella del contenido'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_imports', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='filename',
            field=models.CharField(max_length=255, verbose_name='nombre de archivo'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='mapping',
            field=models.JSONField(default=dict, verbose_name='asignación de columnas'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='preview',
            field=models.JSONField(default=list, verbose_name='previsualización'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='result',
            field=models.JSONField(default=dict, verbose_name='resultado'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('preview', 'Previsualización'), ('confirmed', 'Confirmada'), ('failed', 'Fallida')], default='preview', max_length=16, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='associations.association', verbose_name='asociación'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(max_length=80, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='members.section', verbose_name='cuerda'),
        ),
        migrations.AlterField(
            model_name='member',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profiles', to=settings.AUTH_USER_MODEL, verbose_name='cuenta'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='member',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='associations.association', verbose_name='asociación'),
        ),
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='member',
            name='external_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='identificador externo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=120, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='member',
            name='kind',
            field=models.CharField(choices=[('musician', 'Músico socio'), ('supporter', 'Socio colaborador/mecenas'), ('external', 'Colaborador musical externo')], default='musician', max_length=16, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=180, verbose_name='apellidos'),
        ),
        migrations.AlterField(
            model_name='member',
            name='national_id',
            field=models.CharField(blank=True, max_length=40, verbose_name='DNI/NIE'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, upload_to=apps.members.models.private_member_photo_path, verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=16, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='memberinstrument',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_instruments', to='members.instrument', verbose_name='instrumento'),
        ),
        migrations.AlterField(
            model_name='memberinstrument',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='principal'),
        ),
        migrations.AlterField(
            model_name='memberinstrument',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_instruments', to='members.member', verbose_name='miembro'),
        ),
        migrations.AlterField(
            model_name='section',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='associations.association', verbose_name='asociación'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=80, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='orden'),
        ),
    ]
