# Generated by Django 5.2.7 on 2026-09-22 07:00

import apps.members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_importbatch_options_alter_instrument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='source_file',
            field=models.FileField(blank=True, upload_to=apps.members.models.private_member_import_path, verbose_name='fichero original temporal'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='source_headers',
            field=models.JSONField(default=list, verbose_name='columnas de origen'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Subido'), ('preview', 'Previsualización'), ('confirmed', 'Confirmada'), ('failed', 'Fallida')], default='uploaded', max_length=16, verbose_name='estado'),
        ),
    ]
