# Generated by Django 5.2.7 on 2026-09-21 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='members.member'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='invitation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='activities.invitation'),
        ),
        migrations.AddField(
            model_name='invitationresponseevent',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitation_response_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitationresponseevent',
            name='invitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_history', to='activities.invitation'),
        ),
        migrations.AddField(
            model_name='programmeitem',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme', to='activities.activity'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['association', 'starts_at'], name='activities__associa_2734fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('activity', 'member'), name='unique_activity_invitation'),
        ),
    ]
