# Generated by Django 5.2.7 on 2026-09-21 07:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
        ('associations', '0002_alter_association_options_and_more'),
        ('members', '0002_alter_importbatch_options_alter_instrument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['starts_at', 'title'], 'verbose_name': 'actividad', 'verbose_name_plural': 'actividades'},
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'asistencia', 'verbose_name_plural': 'asistencias'},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': 'convocatoria', 'verbose_name_plural': 'convocatorias'},
        ),
        migrations.AlterModelOptions(
            name='invitationresponseevent',
            options={'ordering': ['created_at'], 'verbose_name': 'cambio de respuesta', 'verbose_name_plural': 'cambios de respuesta'},
        ),
        migrations.AlterModelOptions(
            name='programmeitem',
            options={'ordering': ['order', 'id'], 'verbose_name': 'elemento de repertorio', 'verbose_name_plural': 'elementos de repertorio'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='associations.association', verbose_name='asociación'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_activities', to=settings.AUTH_USER_MODEL, verbose_name='creada por'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='final'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='kind',
            field=models.CharField(choices=[('rehearsal', 'Ensayo'), ('performance', 'Actuación')], max_length=16, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='lugar'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='meeting_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='hora de concentración'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='response_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='plazo de respuesta'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='starts_at',
            field=models.DateTimeField(verbose_name='inicio'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicada'), ('cancelled', 'Cancelada'), ('completed', 'Completada')], default='draft', max_length=16, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=180, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='uniform',
            field=models.CharField(blank=True, max_length=255, verbose_name='uniforme'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='versión'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='invitation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='activities.invitation', verbose_name='convocatoria'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='note',
            field=models.CharField(blank=True, max_length=500, verbose_name='nota'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='recorded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de registro'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='registrada por'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('unrecorded', 'Sin registrar'), ('present', 'Presente'), ('absent', 'Ausente'), ('excused', 'Ausencia justificada')], default='unrecorded', max_length=16, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='activities.activity', verbose_name='actividad'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='activity_version',
            field=models.PositiveIntegerField(default=1, verbose_name='versión de la actividad'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='members.member', verbose_name='miembro'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de respuesta'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='response',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('declined', 'Rechazada')], default='pending', max_length=16, verbose_name='respuesta'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='response_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='nota de respuesta'),
        ),
        migrations.AlterField(
            model_name='invitationresponseevent',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitation_response_events', to=settings.AUTH_USER_MODEL, verbose_name='modificada por'),
        ),
        migrations.AlterField(
            model_name='invitationresponseevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='invitationresponseevent',
            name='invitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_history', to='activities.invitation', verbose_name='convocatoria'),
        ),
        migrations.AlterField(
            model_name='invitationresponseevent',
            name='note',
            field=models.CharField(blank=True, max_length=500, verbose_name='nota'),
        ),
        migrations.AlterField(
            model_name='invitationresponseevent',
            name='response',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('declined', 'Rechazada')], max_length=16, verbose_name='respuesta'),
        ),
        migrations.AlterField(
            model_name='programmeitem',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme', to='activities.activity', verbose_name='actividad'),
        ),
        migrations.AlterField(
            model_name='programmeitem',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notas'),
        ),
        migrations.AlterField(
            model_name='programmeitem',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='programmeitem',
            name='title',
            field=models.CharField(max_length=180, verbose_name='título'),
        ),
    ]
