# Generated by Django 5.2.7 on 2026-09-21 06:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('associations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=12)),
                ('push_token', models.CharField(max_length=512)),
                ('permission', models.CharField(choices=[('unknown', 'Desconocido'), ('granted', 'Concedido'), ('denied', 'Denegado'), ('provisional', 'Provisional'), ('disabled', 'Desactivado')], default='unknown', max_length=16)),
                ('last_receipt_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('deep_link', models.CharField(blank=True, max_length=255)),
                ('deduplication_key', models.CharField(max_length=255, unique=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='activities.activity')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='associations.association')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('push', 'Push'), ('email', 'Correo')], max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviada'), ('failed', 'Fallida')], default='pending', max_length=12)),
                ('provider_id', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='communications.deviceregistration')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='communications.notification')),
            ],
        ),
        migrations.AddConstraint(
            model_name='deviceregistration',
            constraint=models.UniqueConstraint(fields=('account', 'push_token'), name='unique_account_push_token'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['account', 'read_at', 'created_at'], name='communicati_account_3e6c0a_idx'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('notification', 'device', 'channel'), name='unique_notification_device_channel'),
        ),
    ]
