# Generated by Django 5.2.7 on 2026-09-21 07:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_options_alter_attendance_options_and_more'),
        ('associations', '0002_alter_association_options_and_more'),
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'entrega de aviso', 'verbose_name_plural': 'entregas de avisos'},
        ),
        migrations.AlterModelOptions(
            name='deviceregistration',
            options={'verbose_name': 'dispositivo registrado', 'verbose_name_plural': 'dispositivos registrados'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'aviso', 'verbose_name_plural': 'avisos'},
        ),
        migrations.AlterField(
            model_name='delivery',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='intentos'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='channel',
            field=models.CharField(choices=[('push', 'Push'), ('email', 'Correo')], max_length=12, verbose_name='canal'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='communications.deviceregistration', verbose_name='dispositivo'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='error',
            field=models.TextField(blank=True, verbose_name='error'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='último intento'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='communications.notification', verbose_name='aviso'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='provider_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='identificador del proveedor'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviada'), ('failed', 'Fallida')], default='pending', max_length=12, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='deviceregistration',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='cuenta'),
        ),
        migrations.AlterField(
            model_name='deviceregistration',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='deviceregistration',
            name='installation_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='identificador de instalación'),
        ),
        migrations.AlterField(
            model_name='deviceregistration',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='deviceregistration',
            name='last_receipt_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='última recepción'),
        ),
        migrations.AlterField(
            model_name='deviceregistration',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True, verbose_name='última conexión'),
        ),
        migrations.AlterField(
            model_name='deviceregistration',
            name='permission',
            field=models.CharField(choices=[('unknown', 'Desconocido'), ('granted', 'Concedido'), ('denied', 'Denegado'), ('provisional', 'Provisional'), ('disabled', 'Desactivado')], default='unknown', max_length=16, verbose_name='permiso'),
        ),
        migrations.AlterField(
            model_name='deviceregistration',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=12, verbose_name='plataforma'),
        ),
        migrations.AlterField(
            model_name='deviceregistration',
            name='push_token',
            field=models.CharField(max_length=512, verbose_name='token push'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='cuenta'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='activities.activity', verbose_name='actividad'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='associations.association', verbose_name='asociación'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='deduplication_key',
            field=models.CharField(max_length=255, unique=True, verbose_name='clave de deduplicación'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='deep_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='enlace interno'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de lectura'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=180, verbose_name='título'),
        ),
    ]
