# Generated by Django 5.2.7 on 2026-09-24 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_delivery_options_and_more'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='polls.poll', verbose_name='encuesta'),
        ),
    ]
