# Generated by Django 5.2.7 on 2026-09-30 15:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def disabled_is_denied(apps, schema_editor):
    """El antiguo estado `disabled` equivale a `denied` en el contrato."""
    DeviceRegistration = apps.get_model("communications", "DeviceRegistration")
    DeviceRegistration.objects.filter(permission="disabled").update(permission="denied")


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_notification_poll'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceregistration',
            name='app_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='versión de la app'),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='locale',
            field=models.CharField(blank=True, max_length=35, verbose_name='idioma'),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de revocación'),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='token_invalidated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='token rechazado por el proveedor'),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='token_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='último cambio de token'),
        ),
        migrations.AlterField(
            model_name='deviceregistration',
            name='last_receipt_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='última recepción confirmada'),
        ),
        migrations.AlterField(
            model_name='deviceregistration',
            name='permission',
            field=models.CharField(choices=[('not_determined', 'Sin decidir'), ('provisional', 'Provisional'), ('granted', 'Concedido'), ('denied', 'Denegado'), ('restricted', 'Restringido'), ('unknown', 'Desconocido')], default='unknown', max_length=16, verbose_name='permiso'),
        ),
        migrations.AlterField(
            model_name='deviceregistration',
            name='push_token',
            field=models.CharField(max_length=4096, verbose_name='token push'),
        ),
        migrations.CreateModel(
            name='PushTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identificador')),
                ('expected_presentation', models.CharField(choices=[('foreground', 'Primer plano'), ('background', 'Segundo plano')], max_length=12, verbose_name='presentación esperada')),
                ('status', models.CharField(choices=[('queued', 'En cola'), ('provider_accepted', 'Aceptada por el proveedor'), ('provider_failed', 'Rechazada por el proveedor'), ('received_foreground', 'Recibida en primer plano'), ('opened_from_background', 'Abierta desde segundo plano'), ('expired', 'Caducada')], default='queued', max_length=24, verbose_name='estado')),
                ('provider_message_id', models.CharField(blank=True, max_length=255, verbose_name='identificador del proveedor')),
                ('provider_error_code', models.CharField(blank=True, max_length=64, verbose_name='código de error del proveedor')),
                ('reported_at', models.DateTimeField(blank=True, null=True, verbose_name='momento indicado por la app')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de confirmación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('expires_at', models.DateTimeField(verbose_name='caducidad')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tests', to=settings.AUTH_USER_MODEL, verbose_name='cuenta')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tests', to='communications.deviceregistration', verbose_name='dispositivo')),
            ],
            options={
                'verbose_name': 'prueba de aviso',
                'verbose_name_plural': 'pruebas de avisos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(disabled_is_denied, migrations.RunPython.noop),
    ]
