# Generated by Django 5.2.7 on 2026-09-21 06:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('car', 'Coche'), ('bus', 'Autobús'), ('other', 'Otro')], max_length=12)),
                ('label', models.CharField(max_length=120)),
                ('meeting_point', models.CharField(blank=True, max_length=255)),
                ('departure_at', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='activities.activity')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driven_transports', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='TransportAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_assignments', to='members.member')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='transport.transport')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('transport', 'member'), name='unique_transport_member'), models.UniqueConstraint(fields=('member', 'transport'), name='unique_member_transport_pair')],
            },
        ),
    ]
