# Generated by Django 5.2.7 on 2026-09-21 07:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_options_alter_attendance_options_and_more'),
        ('members', '0002_alter_importbatch_options_alter_instrument_options_and_more'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'transporte', 'verbose_name_plural': 'transportes'},
        ),
        migrations.AlterModelOptions(
            name='transportassignment',
            options={'verbose_name': 'asignación de transporte', 'verbose_name_plural': 'asignaciones de transporte'},
        ),
        migrations.AlterField(
            model_name='transport',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='activities.activity', verbose_name='actividad'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='capacity',
            field=models.PositiveSmallIntegerField(verbose_name='plazas'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='departure_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='hora de salida'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driven_transports', to='members.member', verbose_name='conductor'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('car', 'Coche'), ('bus', 'Autobús'), ('other', 'Otro')], max_length=12, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='label',
            field=models.CharField(max_length=120, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='meeting_point',
            field=models.CharField(blank=True, max_length=255, verbose_name='punto de encuentro'),
        ),
        migrations.AlterField(
            model_name='transportassignment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_assignments', to='members.member', verbose_name='miembro'),
        ),
        migrations.AlterField(
            model_name='transportassignment',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='transport.transport', verbose_name='transporte'),
        ),
    ]
